package com.example.aluno.ifapp.databaseModel;

import android.content.Context;

import static com.example.aluno.ifapp.databaseModel.CursoDAO.*;

/**
 * Created by dangh on 26/05/2018.
 */

public class DisciplinaDAO {
    private MainDatabase db;

    public DisciplinaDAO(Context ctx) {
        db = MainDatabase.getInstance(ctx);
    }

    public static final String DISCIPLINA_TABELA = "disciplina";

    //DISCIPLINA COLUNAS
    public static final String COL_1_DISC = "pk_disciplina";
    public static final String COL_2_DISC = "nome";
    public static final String COL_3_DISC = "ementa";
    public static final String COL_4_DISC = "fk_curso";

    public static String dropTabelaDisciplina(){
        return "DROP TABLE IF EXISTS"+ DISCIPLINA_TABELA;
    }

    public static String criaTabelaDisciplina(){
        String CRIA_DISCIPLINA = "CREATE TABLE " + DISCIPLINA_TABELA
                + "(" + COL_1_DISC + " INTEGER PRIMARY KEY AUTOINCREMENT, "
                + COL_2_DISC + " TEXT, "
                + COL_3_DISC + " TEXT, "
                + COL_4_DISC + " INTEGER NOT NULL, "
                + "FOREIGN KEY (" + COL_4_DISC + ") REFERENCES " + CURSO_TABELA + "(" + COL_1_CURSO + "));";
        return CRIA_DISCIPLINA;
    }


    String [][] DisciplinasAdm1 = new String[][] {
            {"Arte","Jogos de integração; Exploração do corpo no espaço; Expressão vocal; Regras do jogo teatral; Conceito de foco; Relação palco/plateia; Elementos da linguagem teatral: cenário, figurino, iluminação, sonoplastia. Improvisação; Exploração de objetos imaginários; Noções de história da arte e estética. Introdução à História do Teatro Grego: a tragédia e a comédia; O Teatro no Renascimento: a Commédia dell Arte; Introdução à História do Teatro no Brasil. Estabelecimento de relações com a arte e a cultura regional, indígena e afrodescendente.\n" , "1"  },
            {"Educação Física", "Atividades de aprendizagem coletiva, jogos e esportes. Metodologia prática e teórica. Aprimoramento das valências físicas.\n", "1"},
            {"Espanhol","Desenvolver diferentes habilidades indispensáveis à comunicação oral e escrita: ler, ouvir, falar e escrever. Conhecer a origem e a formação do idioma Espanhol. Conhecer o alfabeto. Conhecer e utilizar adequadamente vocabulário específico sobre cumprimentos e saudações, apresentação pessoal, partes do corpo, roupas, partes da casa, alimentos, alimentação nutricional, dias da semana e meses do ano, números, horas e verbos de rotina. Reconhecer e utilizar adequadamente os pronomes de tratamento e os verbos em tú e usted.\n", "1"},
            {"Inglês","Competência comunicativa, análise de estruturas linguísticas da Língua Inglesa. Entendimento de expressões da língua. Diferentes estratégias e técnicas de leitura. Manipulação de Softwares de tradução automática. Vocabulário técnico. Ênfase para a leitura e entendimento, visando à preparação do estudante para a elaboração textos.\n","1"},
            {"Português","A linguagem como manifestação da cultura e como constituidora dos sujeitos sociais. Leitura e interpretação de textos em linguagens não verbais: pinturas, ilustrações, colagens, fotos, publicidade, charges, tiras, quadrinho. A importância da leitura. Tipologia textual. Tipos de parágrafos. A ligação de parágrafos. A língua padrão e seu funcionamento social. Coesão e coerência textuais. Fonética e fonologia. Morfologia. Texto literário e texto não-literário. A literatura como manifestação cultural de uma sociedade específica. Gêneros textuais. Leitura e análise de poemas, contos e romances dos autores mais representativos da literatura.","1"},
            {"Filosofia","O estudo de Filosofia. Sua origem e nascimento. Seus campos do conhecimento, principais períodos de sua história e seus aspectos contemporâneos.","1"},
            {"Geografia","INTRODUÇÃO AOS ESTUDOS GEOGRÁFICOS. FUNDAMENTOS DE CARTOGRAFIA Planeta Terra: coordenadas, movimentos e fusos horários. Representações cartográficas, escalas e projeções. Mapas temáticos e gráficos. Tecnologias modernas utilizadas pela Cartografia. GEOGRAFIA FÍSICA E MEIO AMBIENTE Estrutura geológica. As estruturas e as formas do relevo. Solo. Clima. Os fenômenos climáticos e a interferência humana. Hidrografia. Biomas e formações vegetais: classificação e situação atual. As conferências em defesa do meio ambiente.","1"},
            {"História","Noções de tempo cronológico e histórico. O ofício do historiador e a plural utilização das fontes de pesquisa. As relações sociais, o comportamento e a cultura das civilizações clássicas. O mundo oriental e as misturas culturais. Islamismo. Formação dos Estados modernos. O Renascimento e suas implicações. O mundo em expansão, as navegações e o começo da globalização do planeta. O poder da Igreja católica. O nascimento do capitalismo e os profundos impactos na história da humanidade.\n","1"},
            {"Sociologia","As origens da Sociologia e as interpretações das relações sociais dos três principais autores da Sociologia: Karl Marx, Émile Durkheim e Max Weber. Analisar a cultura, considerando aspectos da diversidade cultural brasileira. Perceber a cultura como um processo de criação. Processos da socialização e as instituições sociais: escola, religião e família.","1"},
            {"Biologia","Introdução às ciências biológicas. Teorias de origem da vida. Biologia Celular e Molecular. Gametogênese e Mutações. Genética Clássica ou Mendeliana. ","1"},
            {"Física","Cinemática, Dinâmica, Energia, Gravitação, Hidrostática, Ondas.","1"},
            {"Química","Introdução à Química; Composição e transformação dos sistemas materiais; Notação e nomenclatura Química; Evolução dos modelos atômicos; Classificação periódica dos elementos; Ligações Químicas; Geometria molecular; Reações Químicas; Massa atômica e massa molecular.","1"},
            {"Matemática","Conjuntos. Funções. Função polinomial. Função modular. Função exponencial. Função logarítmica. Progressões. Noções de matemática financeira.","1"},
            {"Fundamentos da Administração","Conceito, Campo e Objetivo da Administração. Teorias da Administração. Novas Tendências em Administração. Princípios e funções administrativas no processo integrado de gestão. Contexto organizacional. Poder, Ideologia e Teoria Administrativa.","1"},
            {"Gestão de Pessoas","Políticas e práticas de recursos humanos. Gestão Estratégica de Pessoas. Educação Corporativa. Recrutamento, seleção, acolhimento e integração. Remuneração e Benefícios. Treinamento e desenvolvimento. Avaliação de desempenho. Qualidade de Vida no Trabalho e Segurança no Trabalho. Rotinas trabalhistas.","1"},
            {"Informática Básica","Informática e sua aplicação em administração. Arquitetura de hardware, de um computador, processadores, dispositivos de entrada e saída e dispositivos de memória. Aprendizagem de ferramentas de software (Sistema Operacional). Editor de texto, planilha eletrônica, apresentações, internet, páginas Web. Gestão de informação eletrônica. Evolução do uso da TI nas empresas.","1"},
            {"Metodologia de Pesquisa Técnica e Científica","Ciência, conhecimento científico, pesquisa e metodologia científica. Os métodos quantitativos e qualitativos. O planejamento da pesquisa: estratégias, amostragem, mensuração, escalas. As fontes e a coleta de dados: explorando dados secundários, métodos de survey, instrumentos para comunicação com o respondente, estudos observacionais, experimentação, o estudo de caso. Análise e apresentação de dados: preparação e descrição de dados, apresentação de resultados: relatórios escritos e orais. Normas da ABNT. Formatação de trabalhos acadêmicos. ","1"},
            {"Gestão de Serviços","Noções básicas de arquivo; técnicas de arquivamento; sistemas de Arquivamento; preservação e conservação de documentos; Comunicação empresarial. Processos administrativos; ferramentas organizacionais (brainstorming, 5w1h); Análise organizacional: organograma, fluxograma, layout, formulários, manuais, e regulamentos; rotina administrativa e processos operacionais; práticas administrativas, controle interno de processos. Interligação com as demais áreas. Política de compras. Controle de materiais. Gestão de estoques. Almoxarifados. Transportes. Código de defesa do consumidor, direitos básicos do consumidor.","1"},



    };

    String [][] DisciplinasInfo1 = new String[][]{
            {"Arte","Jogos de integração; Exploração do corpo no espaço; Expressão vocal; Regras do jogo teatral; Conceito de foco; Relação palco/plateia; Elementos da linguagem teatral: cenário, figurino, iluminação, sonoplastia. Improvisação; Exploração de objetos imaginários; Noções de história da arte e estética. Introdução à História do Teatro Grego: a tragédia e a comédia; O Teatro no Renascimento: a Commédia dell Arte; Introdução à História do Teatro no Brasil. Estabelecimento de relações com a arte e a cultura regional, indígena e afrodescendente.\n" , "1"  },
            {"Educação Física", "Atividades de aprendizagem coletiva, jogos e esportes. Metodologia prática e teórica. Aprimoramento das valências físicas.\n", "1"},
            {"Espanhol","Desenvolver diferentes habilidades indispensáveis à comunicação oral e escrita: ler, ouvir, falar e escrever. Conhecer a origem e a formação do idioma Espanhol. Conhecer o alfabeto. Conhecer e utilizar adequadamente vocabulário específico sobre cumprimentos e saudações, apresentação pessoal, partes do corpo, roupas, partes da casa, alimentos, alimentação nutricional, dias da semana e meses do ano, números, horas e verbos de rotina. Reconhecer e utilizar adequadamente os pronomes de tratamento e os verbos em tú e usted.\n", "1"},
            {"Inglês","Competência comunicativa, análise de estruturas linguísticas da Língua Inglesa. Entendimento de expressões da língua. Diferentes estratégias e técnicas de leitura. Manipulação de Softwares de tradução automática. Vocabulário técnico. Ênfase para a leitura e entendimento, visando à preparação do estudante para a elaboração textos.\n","1"},
            {"Português","A linguagem como manifestação da cultura e como constituidora dos sujeitos sociais. Leitura e interpretação de textos em linguagens não verbais: pinturas, ilustrações, colagens, fotos, publicidade, charges, tiras, quadrinho. A importância da leitura. Tipologia textual. Tipos de parágrafos. A ligação de parágrafos. A língua padrão e seu funcionamento social. Coesão e coerência textuais. Fonética e fonologia. Morfologia. Texto literário e texto não-literário. A literatura como manifestação cultural de uma sociedade específica. Gêneros textuais. Leitura e análise de poemas, contos e romances dos autores mais representativos da literatura.","1"},
            {"Filosofia","O estudo de Filosofia. Sua origem e nascimento. Seus campos do conhecimento, principais períodos de sua história e seus aspectos contemporâneos.","1"},
            {"Geografia","INTRODUÇÃO AOS ESTUDOS GEOGRÁFICOS. FUNDAMENTOS DE CARTOGRAFIA Planeta Terra: coordenadas, movimentos e fusos horários. Representações cartográficas, escalas e projeções. Mapas temáticos e gráficos. Tecnologias modernas utilizadas pela Cartografia. GEOGRAFIA FÍSICA E MEIO AMBIENTE Estrutura geológica. As estruturas e as formas do relevo. Solo. Clima. Os fenômenos climáticos e a interferência humana. Hidrografia. Biomas e formações vegetais: classificação e situação atual. As conferências em defesa do meio ambiente.","1"},
            {"História","Noções de tempo cronológico e histórico. O ofício do historiador e a plural utilização das fontes de pesquisa. As relações sociais, o comportamento e a cultura das civilizações clássicas. O mundo oriental e as misturas culturais. Islamismo. Formação dos Estados modernos. O Renascimento e suas implicações. O mundo em expansão, as navegações e o começo da globalização do planeta. O poder da Igreja católica. O nascimento do capitalismo e os profundos impactos na história da humanidade.\n","1"},
            {"Sociologia","As origens da Sociologia e as interpretações das relações sociais dos três principais autores da Sociologia: Karl Marx, Émile Durkheim e Max Weber. Analisar a cultura, considerando aspectos da diversidade cultural brasileira. Perceber a cultura como um processo de criação. Processos da socialização e as instituições sociais: escola, religião e família.","1"},
            {"Biologia","Introdução às ciências biológicas. Teorias de origem da vida. Biologia Celular e Molecular. Gametogênese e Mutações. Genética Clássica ou Mendeliana. ","1"},
            {"Física","Cinemática, Dinâmica, Energia, Gravitação, Hidrostática, Ondas.","1"},
            {"Química","Introdução à Química; Composição e transformação dos sistemas materiais; Notação e nomenclatura Química; Evolução dos modelos atômicos; Classificação periódica dos elementos; Ligações Químicas; Geometria molecular; Reações Químicas; Massa atômica e massa molecular.","1"},
            {"Matemática","Conjuntos. Funções. Função polinomial. Função modular. Função exponencial. Função logarítmica. Progressões. Noções de matemática financeira.","1"},
            {"Desenvolvimento Web","Estruturação de páginas Web com HTML. Formatação de estilo e apresentação de páginas Web com CSS. Padrões Web.","1"},
            {"Fundamentos da Informática","Histórico da Informática. Noções de Hardware e Software: Sistemas Operacionais, Redes de Computadores, Segurança, Bancos de Dados e Internet. Sistemas Numéricos. Conceitos de Sistemas de Informação. O Profissional da Informática. Informática e Sociedade. Informática e Meio Ambiente. Aspectos Legais do Software.","1"},
            {"Lógica da Programação","Introdução à lógica de programação. Conceitos básicos sobre algoritmos. Metodologia de desenvolvimento de algoritmos. Tipos de dados. Variáveis e constantes. Expressões e operadores relacionais, aritméticos e lógicos. Estruturas de controle, repetição e seleção. Vetores e Matrizes. Introdução a linguagem de programação. Implementação de Algoritmos.","1"},
            {"Infraestrutura de Redes","Redes cabeadas e Redes sem fio. Equipamentos básicos de rede (Hub, Switch, Repetidores, Roteador, Cabeamento Estruturado). Configuração de roteador/switches (comandos, criação de vlans). Montagem de pequenas Redes. Compartilhamento de arquivos e impressoras. Montagem de servidores de rede.","1"},

    };

    String [][] DisciplinasVest1 = new String[][]{
            {"Arte","Jogos de integração; Exploração do corpo no espaço; Expressão vocal; Regras do jogo teatral; Conceito de foco; Relação palco/plateia; Elementos da linguagem teatral: cenário, figurino, iluminação, sonoplastia. Improvisação; Exploração de objetos imaginários; Noções de história da arte e estética. Introdução à História do Teatro Grego: a tragédia e a comédia; O Teatro no Renascimento: a Commédia dell Arte; Introdução à História do Teatro no Brasil. Estabelecimento de relações com a arte e a cultura regional, indígena e afrodescendente.\n" , "1"  },
            {"Educação Física", "Atividades de aprendizagem coletiva, jogos e esportes. Metodologia prática e teórica. Aprimoramento das valências físicas.\n", "1"},
            {"Espanhol","Desenvolver diferentes habilidades indispensáveis à comunicação oral e escrita: ler, ouvir, falar e escrever. Conhecer a origem e a formação do idioma Espanhol. Conhecer o alfabeto. Conhecer e utilizar adequadamente vocabulário específico sobre cumprimentos e saudações, apresentação pessoal, partes do corpo, roupas, partes da casa, alimentos, alimentação nutricional, dias da semana e meses do ano, números, horas e verbos de rotina. Reconhecer e utilizar adequadamente os pronomes de tratamento e os verbos em tú e usted.\n", "1"},
            {"Inglês","Competência comunicativa, análise de estruturas linguísticas da Língua Inglesa. Entendimento de expressões da língua. Diferentes estratégias e técnicas de leitura. Manipulação de Softwares de tradução automática. Vocabulário técnico. Ênfase para a leitura e entendimento, visando à preparação do estudante para a elaboração textos.\n","1"},
            {"Português","A linguagem como manifestação da cultura e como constituidora dos sujeitos sociais. Leitura e interpretação de textos em linguagens não verbais: pinturas, ilustrações, colagens, fotos, publicidade, charges, tiras, quadrinho. A importância da leitura. Tipologia textual. Tipos de parágrafos. A ligação de parágrafos. A língua padrão e seu funcionamento social. Coesão e coerência textuais. Fonética e fonologia. Morfologia. Texto literário e texto não-literário. A literatura como manifestação cultural de uma sociedade específica. Gêneros textuais. Leitura e análise de poemas, contos e romances dos autores mais representativos da literatura.","1"},
            {"Filosofia","O estudo de Filosofia. Sua origem e nascimento. Seus campos do conhecimento, principais períodos de sua história e seus aspectos contemporâneos.","1"},
            {"Geografia","INTRODUÇÃO AOS ESTUDOS GEOGRÁFICOS. FUNDAMENTOS DE CARTOGRAFIA Planeta Terra: coordenadas, movimentos e fusos horários. Representações cartográficas, escalas e projeções. Mapas temáticos e gráficos. Tecnologias modernas utilizadas pela Cartografia. GEOGRAFIA FÍSICA E MEIO AMBIENTE Estrutura geológica. As estruturas e as formas do relevo. Solo. Clima. Os fenômenos climáticos e a interferência humana. Hidrografia. Biomas e formações vegetais: classificação e situação atual. As conferências em defesa do meio ambiente.","1"},
            {"História","Noções de tempo cronológico e histórico. O ofício do historiador e a plural utilização das fontes de pesquisa. As relações sociais, o comportamento e a cultura das civilizações clássicas. O mundo oriental e as misturas culturais. Islamismo. Formação dos Estados modernos. O Renascimento e suas implicações. O mundo em expansão, as navegações e o começo da globalização do planeta. O poder da Igreja católica. O nascimento do capitalismo e os profundos impactos na história da humanidade.\n","1"},
            {"Sociologia","As origens da Sociologia e as interpretações das relações sociais dos três principais autores da Sociologia: Karl Marx, Émile Durkheim e Max Weber. Analisar a cultura, considerando aspectos da diversidade cultural brasileira. Perceber a cultura como um processo de criação. Processos da socialização e as instituições sociais: escola, religião e família.","1"},
            {"Biologia","Introdução às ciências biológicas. Teorias de origem da vida. Biologia Celular e Molecular. Gametogênese e Mutações. Genética Clássica ou Mendeliana. ","1"},
            {"Física","Cinemática, Dinâmica, Energia, Gravitação, Hidrostática, Ondas.","1"},
            {"Química","Introdução à Química; Composição e transformação dos sistemas materiais; Notação e nomenclatura Química; Evolução dos modelos atômicos; Classificação periódica dos elementos; Ligações Químicas; Geometria molecular; Reações Químicas; Massa atômica e massa molecular.","1"},
            {"Matemática","Conjuntos. Funções. Função polinomial. Função modular. Função exponencial. Função logarítmica. Progressões. Noções de matemática financeira.","1"},
            {"Desenho Técnico","Desenho técnico manual e computadorizado. Representação gráfica plana de peças do vestuário manual e computadorizada. Planificação do vestuário em escala. Projeções do vestuário. Escala e proporções. Desenho técnico plano da figura humana e suas proporções. Ficha técnica para peça piloto e de produção. A importância da ficha técnica na indústria de confecção. Detalhamento e construção de ficha técnica. Execução de ficha técnica com apoio de sistema computadorizado."},
            {"História do Vestuário","Desenvolvimento histórico do vestuário. Evolução da indumentária e da moda nos séculos XVIII e XIX. A Alta Costura e o Prêt-à-Porter. Século XX e XXI. A moda no Brasil."},
            {"Modelagem I","Princípios da modelagem manual. Diagrama de bases de modelagem em tecidos planos. Modelagem feminina, masculina e infantil em tecido plano. Diagrama de bases de modelagem em tecidos de malha. Modelagem feminina masculina e infantil em malha. Gradação de modelos. Interpretação de modelos. Conceitos e princípios ergonômicos. Teoria Antropométrica. Antropometria aplicada modelagem. Concepção e detalhamento ergonômico de projetos de produto de vestuário. Relações homem-ambiente-vestuário."},
            {"Projeto Integrador I","Elaboração e execução de um projeto que envolva os componentes curriculares do primeiro ano, antepondo o conhecimento obtido através dos conteúdos de cada disciplina."},
            {"Tecnologia da Costura I","Propriedades da costura. Operações básicas de costura. Métodos e processos de confecção adequados ao produto produzido. Prática de costura em tecido plano e malharia. Sequência operacional. Preparação e montagem de peças do vestuário com sequência de operações. "},
            {"Tecnologia Risco e Corte","Introdução às técnicas de risco e corte. Cálculos e planejamento. Tipos de equipamentos de corte Máquinas de enfesto. Qualidade no processo."},
            {"Tecnologia Têxtil",""}
    };

    String [][] DisciplinasAdm2 = new String[][]{
            {"Arte", "O sistema de Constantin Stanislavski. Conceito de ação física. Jogos dramáticos. Criação de cena. Expressão vocal do ator: a voz e suas relações com a palavra, com as emoções, com a pontuação e o estilo do texto. Composição do personagem. O corpo do ator em cena. Preparação corporal: alongamento, agilidade, flexibilidade corporal. Teatro Dramático x Teatro Épico. O realismo. O naturalismo. O simbolismo. O expressionismo. Teatro do Absurdo.","2" },
            {"Educação Física","Noções de antropometria e cinesiologia. Noções de Ginástica. Atividades de aprendizagem coletiva, jogos e esportes. Futebol no Brasil e no mundo. Atletismo:  contextualização. Educação Física e saúde, educação alimentar e nutricional. Aprimoramento das valências.","2"},
            {"Espanhol","Desenvolver diferentes habilidades indispensáveis à comunicação oral e escrita: ler, ouvir, falar e escrever. Conhecer e utilizar vocabulário específico sobre cidades, meios de transporte e esportes. Reconhecer e utilizar adequadamente os falsos amigos. Conhecer alguns ditados populares.","2"},
            {"Inglês","Desenvolvimento da competência comunicativa de nível médio por meio da análise de estruturas linguísticas da Língua Inglesa. Entendimento de expressões da língua. Diferentes estratégias e técnicas de leitura. Manipulação de Softwares de tradução automática. Vocabulário técnico. Ênfase para a leitura e entendimento, visando à preparação do estudante para a elaboração textos.","2"},
            {"Português","Identificação e reconhecimento de verbos em um determinado contexto, percebendo os diferentes tempos verbais de acordo com a ideia que expressam. Aperfeiçoamento das habilidades de compreensão de texto, da linguagem, redação, argumentação e leitura. Morfologia e semântica. Produção textual: paráfrase, parágrafo, descrição, narração, dissertação/argumentação, resumos, relatórios. Leitura e interpretação de textos em linguagens não verbais: pinturas, ilustrações, colagens, fotos, publicidade, charges, tiras, quadrinho. Literatura como projeto de construção de identidade. Estudo dos gêneros e períodos literários. Estudo da cultura afro-brasileira e indígena. Análise de diferentes estilos literários. A literatura como manifestação cultural da sociedade brasileira. Os estilos de época como retrato da evolução cultural e social do Brasil, sua evolução discursiva e ideológica. ","2"},
            {"Filosofia","Compreender a verdade e sua relação com a ignorância. As concepções de verdade e a busca desta. Aspectos referentes ao conhecimento, a preocupação com este, a percepção e a memória. Processo de envelhecimento, respeito e valorização ao idoso.","2"},
            {"Geografia","MUNDO CONTEMPOR NEO: ECONOMIA, GEOPOLÍTICA E SOCIEDADE O processo de desenvolvimento do capitalismo. A globalização. Desenvolvimento humano: as diferenças entre os países e os objetivos do milênio. Ordem geopolítica e econômica: do pós-guerra aos dias de hoje. Conflitos armados no mundo. Educação em  direitos humanos. INDUSTRIALIZAÇÃO E COMÉRCIO INTERNACIONAL A Geografia das indústrias. Países pioneiros no processo de industrialização. Países de industrialização tardia. Países de industrialização planificada. Países recentemente industrializados. O comércio internacional e os principais blocos regionais.","2"},
            {"História","A constituição da identidade das populações do continente americano. Aspectos sociais, econômicos e culturais dos povos pré-colombianos. A chegada dos europeus no continente americano. Os processos de colonização da América: os movimentos sociais e as relações de trabalho decorrentes deste processo histórico. A era das revoluções, desenvolvimento da indústria, transformações nas relações humanas e de trabalho. A organização social e comportamental, os hábitos de consumo. As ideias de liberdade, igualdade e fraternidade e as revoluções liberais. Os processos de independência das colônias. Movimentos trabalhistas e o advento do socialismo. As mudanças na América Latina.","2"},
            {"Sociologia","As mudanças no mundo contemporâneo: a globalização, a interação social, a vida cotidiana e educação para o trânsito. O trabalho como fenômeno social. Classe, Estratificação e Desigualdade. A mídia. Analisar o crime e o desvio.","2"},
            {"Biologia","Embriologia e Histologia Animal. Fisiologia humana: o funcionamento do nosso organismo. Educação alimentar e nutricional. Classificação Biológica. Zoologia: a biodiversidade animal. Poríferos, acnidários, helmintos, anelídeos, moluscos, artrópodes, equinodermos e cordados.","2"},
            {"Física","Termologia, Estudo dos Gases, Termodinâmica, Ótica, Ondas, Física Moderna.","2"},
            {"Química","Cálculos estequiométricos; Soluções; Termoquímica; Cinética química; Equilíbrio químico; Eletroquímica.","2"},
            {"Matemática","Trigonometria nos triângulos. Trigonometria no ciclo. Matrizes. Determinantes. Sistemas lineares. Análise combinatória. Probabilidade.","2"},
    };

    String [][] DisciplinasInfo2 = new String[][]{
            {"Arte", "O sistema de Constantin Stanislavski. Conceito de ação física. Jogos dramáticos. Criação de cena. Expressão vocal do ator: a voz e suas relações com a palavra, com as emoções, com a pontuação e o estilo do texto. Composição do personagem. O corpo do ator em cena. Preparação corporal: alongamento, agilidade, flexibilidade corporal. Teatro Dramático x Teatro Épico. O realismo. O naturalismo. O simbolismo. O expressionismo. Teatro do Absurdo.","2" },
            {"Educação Física","Noções de antropometria e cinesiologia. Noções de Ginástica. Atividades de aprendizagem coletiva, jogos e esportes. Futebol no Brasil e no mundo. Atletismo:  contextualização. Educação Física e saúde, educação alimentar e nutricional. Aprimoramento das valências.","2"},
            {"Espanhol","Desenvolver diferentes habilidades indispensáveis à comunicação oral e escrita: ler, ouvir, falar e escrever. Conhecer e utilizar vocabulário específico sobre cidades, meios de transporte e esportes. Reconhecer e utilizar adequadamente os falsos amigos. Conhecer alguns ditados populares.","2"},
            {"Inglês","Desenvolvimento da competência comunicativa de nível médio por meio da análise de estruturas linguísticas da Língua Inglesa. Entendimento de expressões da língua. Diferentes estratégias e técnicas de leitura. Manipulação de Softwares de tradução automática. Vocabulário técnico. Ênfase para a leitura e entendimento, visando à preparação do estudante para a elaboração textos.","2"},
            {"Português","Identificação e reconhecimento de verbos em um determinado contexto, percebendo os diferentes tempos verbais de acordo com a ideia que expressam. Aperfeiçoamento das habilidades de compreensão de texto, da linguagem, redação, argumentação e leitura. Morfologia e semântica. Produção textual: paráfrase, parágrafo, descrição, narração, dissertação/argumentação, resumos, relatórios. Leitura e interpretação de textos em linguagens não verbais: pinturas, ilustrações, colagens, fotos, publicidade, charges, tiras, quadrinho. Literatura como projeto de construção de identidade. Estudo dos gêneros e períodos literários. Estudo da cultura afro-brasileira e indígena. Análise de diferentes estilos literários. A literatura como manifestação cultural da sociedade brasileira. Os estilos de época como retrato da evolução cultural e social do Brasil, sua evolução discursiva e ideológica. ","2"},
            {"Filosofia","Compreender a verdade e sua relação com a ignorância. As concepções de verdade e a busca desta. Aspectos referentes ao conhecimento, a preocupação com este, a percepção e a memória. Processo de envelhecimento, respeito e valorização ao idoso.","2"},
            {"Geografia","MUNDO CONTEMPOR NEO: ECONOMIA, GEOPOLÍTICA E SOCIEDADE O processo de desenvolvimento do capitalismo. A globalização. Desenvolvimento humano: as diferenças entre os países e os objetivos do milênio. Ordem geopolítica e econômica: do pós-guerra aos dias de hoje. Conflitos armados no mundo. Educação em  direitos humanos. INDUSTRIALIZAÇÃO E COMÉRCIO INTERNACIONAL A Geografia das indústrias. Países pioneiros no processo de industrialização. Países de industrialização tardia. Países de industrialização planificada. Países recentemente industrializados. O comércio internacional e os principais blocos regionais.","2"},
            {"História","A constituição da identidade das populações do continente americano. Aspectos sociais, econômicos e culturais dos povos pré-colombianos. A chegada dos europeus no continente americano. Os processos de colonização da América: os movimentos sociais e as relações de trabalho decorrentes deste processo histórico. A era das revoluções, desenvolvimento da indústria, transformações nas relações humanas e de trabalho. A organização social e comportamental, os hábitos de consumo. As ideias de liberdade, igualdade e fraternidade e as revoluções liberais. Os processos de independência das colônias. Movimentos trabalhistas e o advento do socialismo. As mudanças na América Latina.","2"},
            {"Sociologia","As mudanças no mundo contemporâneo: a globalização, a interação social, a vida cotidiana e educação para o trânsito. O trabalho como fenômeno social. Classe, Estratificação e Desigualdade. A mídia. Analisar o crime e o desvio.","2"},
            {"Biologia","Embriologia e Histologia Animal. Fisiologia humana: o funcionamento do nosso organismo. Educação alimentar e nutricional. Classificação Biológica. Zoologia: a biodiversidade animal. Poríferos, acnidários, helmintos, anelídeos, moluscos, artrópodes, equinodermos e cordados.","2"},
            {"Física","Termologia, Estudo dos Gases, Termodinâmica, Ótica, Ondas, Física Moderna.","2"},
            {"Química","Cálculos estequiométricos; Soluções; Termoquímica; Cinética química; Equilíbrio químico; Eletroquímica.","2"},
            {"Matemática","Trigonometria nos triângulos. Trigonometria no ciclo. Matrizes. Determinantes. Sistemas lineares. Análise combinatória. Probabilidade.","2"},
    };

    String [][] DisciplinasVest2 = new String[][]{
            {"Arte", "O sistema de Constantin Stanislavski. Conceito de ação física. Jogos dramáticos. Criação de cena. Expressão vocal do ator: a voz e suas relações com a palavra, com as emoções, com a pontuação e o estilo do texto. Composição do personagem. O corpo do ator em cena. Preparação corporal: alongamento, agilidade, flexibilidade corporal. Teatro Dramático x Teatro Épico. O realismo. O naturalismo. O simbolismo. O expressionismo. Teatro do Absurdo.","2" },
            {"Educação Física","Noções de antropometria e cinesiologia. Noções de Ginástica. Atividades de aprendizagem coletiva, jogos e esportes. Futebol no Brasil e no mundo. Atletismo:  contextualização. Educação Física e saúde, educação alimentar e nutricional. Aprimoramento das valências.","2"},
            {"Espanhol","Desenvolver diferentes habilidades indispensáveis à comunicação oral e escrita: ler, ouvir, falar e escrever. Conhecer e utilizar vocabulário específico sobre cidades, meios de transporte e esportes. Reconhecer e utilizar adequadamente os falsos amigos. Conhecer alguns ditados populares.","2"},
            {"Inglês","Desenvolvimento da competência comunicativa de nível médio por meio da análise de estruturas linguísticas da Língua Inglesa. Entendimento de expressões da língua. Diferentes estratégias e técnicas de leitura. Manipulação de Softwares de tradução automática. Vocabulário técnico. Ênfase para a leitura e entendimento, visando à preparação do estudante para a elaboração textos.","2"},
            {"Português","Identificação e reconhecimento de verbos em um determinado contexto, percebendo os diferentes tempos verbais de acordo com a ideia que expressam. Aperfeiçoamento das habilidades de compreensão de texto, da linguagem, redação, argumentação e leitura. Morfologia e semântica. Produção textual: paráfrase, parágrafo, descrição, narração, dissertação/argumentação, resumos, relatórios. Leitura e interpretação de textos em linguagens não verbais: pinturas, ilustrações, colagens, fotos, publicidade, charges, tiras, quadrinho. Literatura como projeto de construção de identidade. Estudo dos gêneros e períodos literários. Estudo da cultura afro-brasileira e indígena. Análise de diferentes estilos literários. A literatura como manifestação cultural da sociedade brasileira. Os estilos de época como retrato da evolução cultural e social do Brasil, sua evolução discursiva e ideológica. ","2"},
            {"Filosofia","Compreender a verdade e sua relação com a ignorância. As concepções de verdade e a busca desta. Aspectos referentes ao conhecimento, a preocupação com este, a percepção e a memória. Processo de envelhecimento, respeito e valorização ao idoso.","2"},
            {"Geografia","MUNDO CONTEMPOR NEO: ECONOMIA, GEOPOLÍTICA E SOCIEDADE O processo de desenvolvimento do capitalismo. A globalização. Desenvolvimento humano: as diferenças entre os países e os objetivos do milênio. Ordem geopolítica e econômica: do pós-guerra aos dias de hoje. Conflitos armados no mundo. Educação em  direitos humanos. INDUSTRIALIZAÇÃO E COMÉRCIO INTERNACIONAL A Geografia das indústrias. Países pioneiros no processo de industrialização. Países de industrialização tardia. Países de industrialização planificada. Países recentemente industrializados. O comércio internacional e os principais blocos regionais.","2"},
            {"História","A constituição da identidade das populações do continente americano. Aspectos sociais, econômicos e culturais dos povos pré-colombianos. A chegada dos europeus no continente americano. Os processos de colonização da América: os movimentos sociais e as relações de trabalho decorrentes deste processo histórico. A era das revoluções, desenvolvimento da indústria, transformações nas relações humanas e de trabalho. A organização social e comportamental, os hábitos de consumo. As ideias de liberdade, igualdade e fraternidade e as revoluções liberais. Os processos de independência das colônias. Movimentos trabalhistas e o advento do socialismo. As mudanças na América Latina.","2"},
            {"Sociologia","As mudanças no mundo contemporâneo: a globalização, a interação social, a vida cotidiana e educação para o trânsito. O trabalho como fenômeno social. Classe, Estratificação e Desigualdade. A mídia. Analisar o crime e o desvio.","2"},
            {"Biologia","Embriologia e Histologia Animal. Fisiologia humana: o funcionamento do nosso organismo. Educação alimentar e nutricional. Classificação Biológica. Zoologia: a biodiversidade animal. Poríferos, acnidários, helmintos, anelídeos, moluscos, artrópodes, equinodermos e cordados.","2"},
            {"Física","Termologia, Estudo dos Gases, Termodinâmica, Ótica, Ondas, Física Moderna.","2"},
            {"Química","Cálculos estequiométricos; Soluções; Termoquímica; Cinética química; Equilíbrio químico; Eletroquímica.","2"},
            {"Matemática","Trigonometria nos triângulos. Trigonometria no ciclo. Matrizes. Determinantes. Sistemas lineares. Análise combinatória. Probabilidade.","2"},
    };

    String [][] DisciplinasAdm3 = new String[][]{
            {"Arte","Partituras de ação. Precisão. Memória. Equilíbrio. Oposição. Modos contemporâneos na construção da cena a partir dos princípios de Jerzy Grotowski, Peter Brook, Artaud e outros teatrólogos da atualidade. Semana de Arte Moderna. Modernismo. As relações entre arte, cultura e sociedade. Performance. Montagem Cênica. A música no Teatro. Reflexões sobre os aspectos caracterizadores da formação cultural brasileira: história e memória dos povos afro-brasileiros e indígenas. Diversidade Cultural.","3"},
            {"Educação Física","Atividades de aprendizagem coletiva, jogos e esportes. Metodologia prática e teórica. Lutas. Tênis de Mesa. Dança e música: contextualização e características. Xadrez. Valências físicas. Educação para o trânsito.","3"},
            {"Espanhol","Desenvolver diferentes habilidades indispensáveis à comunicação oral e escrita: ler, ouvir, falar e escrever. Reconhecer e utilizar adequadamente os falsos amigos, os heterogenéricos, os heterotónicos e os verbos nos modos subjuntivo e imperativo. Ler e estudar algumas obras clássicas de escritores hispanofalantes de diferentes gêneros textuais: conto, poema, crônica e romance. Estudar compreensão leitora e gramática para o ENEM.\n","3"},
            {"Inglês","Desenvolvimento da competência comunicativa de nível médio por meio da análise de estruturas linguísticas da Língua Inglesa. Entendimento de expressões da língua. Diferentes estratégias e técnicas de leitura. Manipulação de Softwares de tradução automática. Vocabulário técnico. Ênfase para a leitura e entendimento, visando à preparação do aluno para a elaboração textos.","3"},
            {"Português","Análise de obras e textos literários e não literários. A obra em sua relação com o universo literário no qual se insere. Leitura e análise de poemas, contos e romances dos autores mais representativos da literatura. Leitura, interpretação e produção de texto. Estudo da sintaxe.","3"},
            {"Filosofia","Imaginação, linguagem e pensamento. Possibilidades da consciência. Ciência: atitude científica, a ciência na história, as ciências da natureza, as ciências humanas, o ideal científico e a razão instrumental. ","3"},
            {"Geografia","BRASIL: INDUSTRIALIZAÇÃO E POLÍTICA ECONÔMICA Industrialização brasileira. A economia brasileira a partir de 1985. ENERGIA E MEIO AMBIENTE A produção mundial de energia. A produção de energia no Brasil. POPULAÇÃO Características e crescimento da população mundial. Os fluxos migratórios e a estrutura da população. A formação e a diversidade cultural da população brasileira. Aspectos demográficos e estrutura da população brasileira. O ESPAÇO URBANO E O PROCESSO DE URBANIZAÇÃO O espaço urbano do mundo contemporâneo. As cidades e a urbanização brasileira. O ESPAÇO RURAL E A PRODUÇÃO 70 AGROPECUÁRIA Organização da produção agropecuária. A agropecuária no Brasil. GEOGRAFIA DE SANTA CATARINA.","3"},
            {"História","Cidadania e República no Brasil. Os conflitos mundiais do século XX e as consequências da corrida capitalista e do Imperialismo europeu. A Revolução Russa e as transformações mundiais. Movimentos sociais e culturais que marcaram as primeiras décadas do século XX. A era Vargas e as relações de trabalho. Globalização e civilização contemporânea, os desafios éticos de um mundo em profundo devir. A Guerra fria, a luta pela hegemonia econômica, as ditaduras e o abuso de poder. A redemocratização. Cotidiano e trabalho em tempos presentes. Tecnologias e revoluções comportamentais.","3"},
            {"Sociologia","O poder, a política e a ideologia na formação do Estado Moderno. Gênero e Sexualidade. Etnicidade. As cidades e os espaços urbanos. Discussões contemporâneas sobre direitos, movimentos sociais e cidadania. Educação em direitos humanos.\n","3"},
            {"Biologia","Botânica: a classificação das plantas. Ecologia. Evolução biológica e Biotecnologia.","3"},
            {"Física","Eletrostática, Eletrodinâmica, Eletromagnetismo e Física Moderna.","3"},
            {"Química","Reações nucleares; Introdução à química orgânica; Hidrocarbonetos; Funções orgânicas; Reações orgânicas; Polímeros sintéticos; Bioquímica.","3"},
            {"Matemática","Geometria analítica. Ponto, reta e plano. Circunferência. Cônicas. Números complexos. Polinômios. Equações polinomiais. Geometria Plana. Geometria Espacial. Noções de estatística. Matemática Financeira.","3"},
    };

    String [][] DisciplinasInfo3 = new String[][]{
            {"Arte","Partituras de ação. Precisão. Memória. Equilíbrio. Oposição. Modos contemporâneos na construção da cena a partir dos princípios de Jerzy Grotowski, Peter Brook, Artaud e outros teatrólogos da atualidade. Semana de Arte Moderna. Modernismo. As relações entre arte, cultura e sociedade. Performance. Montagem Cênica. A música no Teatro. Reflexões sobre os aspectos caracterizadores da formação cultural brasileira: história e memória dos povos afro-brasileiros e indígenas. Diversidade Cultural.","3"},
            {"Educação Física","Atividades de aprendizagem coletiva, jogos e esportes. Metodologia prática e teórica. Lutas. Tênis de Mesa. Dança e música: contextualização e características. Xadrez. Valências físicas. Educação para o trânsito.","3"},
            {"Espanhol","Desenvolver diferentes habilidades indispensáveis à comunicação oral e escrita: ler, ouvir, falar e escrever. Reconhecer e utilizar adequadamente os falsos amigos, os heterogenéricos, os heterotónicos e os verbos nos modos subjuntivo e imperativo. Ler e estudar algumas obras clássicas de escritores hispanofalantes de diferentes gêneros textuais: conto, poema, crônica e romance. Estudar compreensão leitora e gramática para o ENEM.\n","3"},
            {"Inglês","Desenvolvimento da competência comunicativa de nível médio por meio da análise de estruturas linguísticas da Língua Inglesa. Entendimento de expressões da língua. Diferentes estratégias e técnicas de leitura. Manipulação de Softwares de tradução automática. Vocabulário técnico. Ênfase para a leitura e entendimento, visando à preparação do aluno para a elaboração textos.","3"},
            {"Português","Análise de obras e textos literários e não literários. A obra em sua relação com o universo literário no qual se insere. Leitura e análise de poemas, contos e romances dos autores mais representativos da literatura. Leitura, interpretação e produção de texto. Estudo da sintaxe.","3"},
            {"Filosofia","Imaginação, linguagem e pensamento. Possibilidades da consciência. Ciência: atitude científica, a ciência na história, as ciências da natureza, as ciências humanas, o ideal científico e a razão instrumental. ","3"},
            {"Geografia","BRASIL: INDUSTRIALIZAÇÃO E POLÍTICA ECONÔMICA Industrialização brasileira. A economia brasileira a partir de 1985. ENERGIA E MEIO AMBIENTE A produção mundial de energia. A produção de energia no Brasil. POPULAÇÃO Características e crescimento da população mundial. Os fluxos migratórios e a estrutura da população. A formação e a diversidade cultural da população brasileira. Aspectos demográficos e estrutura da população brasileira. O ESPAÇO URBANO E O PROCESSO DE URBANIZAÇÃO O espaço urbano do mundo contemporâneo. As cidades e a urbanização brasileira. O ESPAÇO RURAL E A PRODUÇÃO 70 AGROPECUÁRIA Organização da produção agropecuária. A agropecuária no Brasil. GEOGRAFIA DE SANTA CATARINA.","3"},
            {"História","Cidadania e República no Brasil. Os conflitos mundiais do século XX e as consequências da corrida capitalista e do Imperialismo europeu. A Revolução Russa e as transformações mundiais. Movimentos sociais e culturais que marcaram as primeiras décadas do século XX. A era Vargas e as relações de trabalho. Globalização e civilização contemporânea, os desafios éticos de um mundo em profundo devir. A Guerra fria, a luta pela hegemonia econômica, as ditaduras e o abuso de poder. A redemocratização. Cotidiano e trabalho em tempos presentes. Tecnologias e revoluções comportamentais.","3"},
            {"Sociologia","O poder, a política e a ideologia na formação do Estado Moderno. Gênero e Sexualidade. Etnicidade. As cidades e os espaços urbanos. Discussões contemporâneas sobre direitos, movimentos sociais e cidadania. Educação em direitos humanos.\n","3"},
            {"Biologia","Botânica: a classificação das plantas. Ecologia. Evolução biológica e Biotecnologia.","3"},
            {"Física","Eletrostática, Eletrodinâmica, Eletromagnetismo e Física Moderna.","3"},
            {"Química","Reações nucleares; Introdução à química orgânica; Hidrocarbonetos; Funções orgânicas; Reações orgânicas; Polímeros sintéticos; Bioquímica.","3"},
            {"Matemática","Geometria analítica. Ponto, reta e plano. Circunferência. Cônicas. Números complexos. Polinômios. Equações polinomiais. Geometria Plana. Geometria Espacial. Noções de estatística. Matemática Financeira.","3"},
    };

    String [][] DisciplinasVest3 = new String[][]{
            {"Arte","Partituras de ação. Precisão. Memória. Equilíbrio. Oposição. Modos contemporâneos na construção da cena a partir dos princípios de Jerzy Grotowski, Peter Brook, Artaud e outros teatrólogos da atualidade. Semana de Arte Moderna. Modernismo. As relações entre arte, cultura e sociedade. Performance. Montagem Cênica. A música no Teatro. Reflexões sobre os aspectos caracterizadores da formação cultural brasileira: história e memória dos povos afro-brasileiros e indígenas. Diversidade Cultural.","3"},
            {"Educação Física","Atividades de aprendizagem coletiva, jogos e esportes. Metodologia prática e teórica. Lutas. Tênis de Mesa. Dança e música: contextualização e características. Xadrez. Valências físicas. Educação para o trânsito.","3"},
            {"Espanhol","Desenvolver diferentes habilidades indispensáveis à comunicação oral e escrita: ler, ouvir, falar e escrever. Reconhecer e utilizar adequadamente os falsos amigos, os heterogenéricos, os heterotónicos e os verbos nos modos subjuntivo e imperativo. Ler e estudar algumas obras clássicas de escritores hispanofalantes de diferentes gêneros textuais: conto, poema, crônica e romance. Estudar compreensão leitora e gramática para o ENEM.\n","3"},
            {"Inglês","Desenvolvimento da competência comunicativa de nível médio por meio da análise de estruturas linguísticas da Língua Inglesa. Entendimento de expressões da língua. Diferentes estratégias e técnicas de leitura. Manipulação de Softwares de tradução automática. Vocabulário técnico. Ênfase para a leitura e entendimento, visando à preparação do aluno para a elaboração textos.","3"},
            {"Português","Análise de obras e textos literários e não literários. A obra em sua relação com o universo literário no qual se insere. Leitura e análise de poemas, contos e romances dos autores mais representativos da literatura. Leitura, interpretação e produção de texto. Estudo da sintaxe.","3"},
            {"Filosofia","Imaginação, linguagem e pensamento. Possibilidades da consciência. Ciência: atitude científica, a ciência na história, as ciências da natureza, as ciências humanas, o ideal científico e a razão instrumental. ","3"},
            {"Geografia","BRASIL: INDUSTRIALIZAÇÃO E POLÍTICA ECONÔMICA Industrialização brasileira. A economia brasileira a partir de 1985. ENERGIA E MEIO AMBIENTE A produção mundial de energia. A produção de energia no Brasil. POPULAÇÃO Características e crescimento da população mundial. Os fluxos migratórios e a estrutura da população. A formação e a diversidade cultural da população brasileira. Aspectos demográficos e estrutura da população brasileira. O ESPAÇO URBANO E O PROCESSO DE URBANIZAÇÃO O espaço urbano do mundo contemporâneo. As cidades e a urbanização brasileira. O ESPAÇO RURAL E A PRODUÇÃO 70 AGROPECUÁRIA Organização da produção agropecuária. A agropecuária no Brasil. GEOGRAFIA DE SANTA CATARINA.","3"},
            {"História","Cidadania e República no Brasil. Os conflitos mundiais do século XX e as consequências da corrida capitalista e do Imperialismo europeu. A Revolução Russa e as transformações mundiais. Movimentos sociais e culturais que marcaram as primeiras décadas do século XX. A era Vargas e as relações de trabalho. Globalização e civilização contemporânea, os desafios éticos de um mundo em profundo devir. A Guerra fria, a luta pela hegemonia econômica, as ditaduras e o abuso de poder. A redemocratização. Cotidiano e trabalho em tempos presentes. Tecnologias e revoluções comportamentais.","3"},
            {"Sociologia","O poder, a política e a ideologia na formação do Estado Moderno. Gênero e Sexualidade. Etnicidade. As cidades e os espaços urbanos. Discussões contemporâneas sobre direitos, movimentos sociais e cidadania. Educação em direitos humanos.\n","3"},
            {"Biologia","Botânica: a classificação das plantas. Ecologia. Evolução biológica e Biotecnologia.","3"},
            {"Física","Eletrostática, Eletrodinâmica, Eletromagnetismo e Física Moderna.","3"},
            {"Química","Reações nucleares; Introdução à química orgânica; Hidrocarbonetos; Funções orgânicas; Reações orgânicas; Polímeros sintéticos; Bioquímica.","3"},
            {"Matemática","Geometria analítica. Ponto, reta e plano. Circunferência. Cônicas. Números complexos. Polinômios. Equações polinomiais. Geometria Plana. Geometria Espacial. Noções de estatística. Matemática Financeira.","3"},
    };




}
